name: "kernel_On_The_GO"   #Name of the workflow_file

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: "Build Kernel"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout kernel source"
      uses: actions/checkout@v2
      with:
        repository:  priyesh2/android_kernel_samsung_a70q-1

    - name: "Set variables"
      id: vars
      run: |
        echo "::set-output name=short_sha::$(git rev-parse HEAD | cut -b 1-8 -)"
        echo "::set-output name=release_name::Storm"

  
    - name: "Android kernel build"
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: ${{ steps.vars.outputs.release_name }}
      with:
        arch: arm64
        compiler: proton-clang/09fb113/binutils
        defconfig: storm_defconfig
        image: Image.gz-dtb

       
    - name: "Alert failed build"
      uses: appleboy/telegram-action@master
      if: ${{ failure() }}
      with:
        to: ${{ secrets.CHANNEL_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: Failed building ${{ steps.vars.outputs.release_name }} on ${{ steps.vars.outputs.short_sha }}, check action for more info. https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

